name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 18

    - name: Move files backend to .
    - uses: actions/checkout@v3
    - run: mv -f backend/* .

    - name: Build with Maven
    - uses: actions/checkout@v3
    - run: mvn clean install

    - name: Login to Docker Hub
    - uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
    - uses: docker/build-push-action@v3
      with:
        push: true
        repository: felipeschirmann/ds-movie
        tags: ${{github.run_number}},latest
