name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 18
    - name: Build with Maven
      run: mvn -f backend/pom.xml clean install
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v2
      with:
       username: ${{ secrets.DOCKER_HUB_USERNAME }}
       password: ${{ secrets.DOCKER_HUB_PASSWORD }}
       repository: felipeschirmann/ds-movie
       tags: ${{github.run_number}},latest
