name: Docker Image CI

on:
  push:
    paths: 
      - "backend/**"
    branches: [ "main" ]
  pull_request:
    paths: 
      - "backend/**"
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: 18
    - name: Build with Maven
      run: |- 
        cd backend
        mvn clean install

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        repository: felipeschirmann/ds-movie
        tags: ${{github.run_number}},latest